apiVersion : apps/v1
kind : Deployment
metadata:
  name : my-deploy
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name : my-container
        image : nginx
        ports :
        - containerPort : 8080
